# Generated by Django 5.0.8 on 2025-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_ownership_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ownership_status',
            field=models.CharField(choices=[('first', 'First Owner'), ('second', 'Second Hand'), ('third', 'Third Hand')], default='first', help_text='Current ownership status of the product', max_length=10),
        ),
    ]
